apiVersion: v1
kind: Service
metadata:
  name: nodeport-service
spec:
  type: NodePort
  selector:
    app: nettools
  ports:
    - port: 80
      name: nginx-port
      targetPort: 80
      nodePort: 30001
    - port: 8080
      name: multitool-port
      targetPort: 8080
      nodePort: 30002