- name: Installing zabbix-agent
  ansible.builtin.apt:
    pkg:
      - zabbix-agent2
      - zabbix-agent2-plugin-*
    state: present
    update_cache: true
    install_recommends: true
  notify:
    - Restart zabbix-agent
