apiVersion: v1
kind: Service
metadata:
  name: deployment-service
spec:
  ports:
    - name: http-app
      port:  80
      protocol: TCP
      targetPort: 80
    - name: https-app
      port:  443
      protocol: TCP
      targetPort: 443
    - name: http-app-multi
      port:  8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: nginx-multitool
