apiVersion: apps/v1
kind: Deployment
metadata:
  name: multitool-busybox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mtool-bbox
  template:
    metadata:
      labels:
        app: mtool-bbox
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ['sh', '-c', 'mkdir -p /sharedvolume && while true; do echo "current date = $(date)" >> /sharedvolume/date.log; sleep 5; done']
        volumeMounts:
          - mountPath: "/sharedvolume"
            name: volume

      - name: multitool
        image: wbitt/network-multitool
        command: ['sh', '-c', 'tail -f /sharedvolume/date.log']
        volumeMounts:
          - name: volume
            mountPath: "/sharedvolume"
      volumes:
        - name: volume
          emptyDir: {}