version: '3.8'
services:
  vologinsm-netology-db:
    image: postgres:15
    container_name: vologinsm-netology-db
    ports:
      - "0.0.0.0:5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_DB: vologinsm-db
      POSTGRES_PASSWORD: vologinsm12!3!!
      PGDATA: /var/lib/postgresql/data/pgdata
    networks:
      vologinsm-my-netology-hw:
        ipv4_address: 172.22.0.2
    restart: always

  vologinsm-pgadmin:
    image: dpage/pgadmin4
    container_name: vologinsm-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: vologinsm@ilove-netology.com
      PGADMIN_DEFAULT_PASSWORD: 123
    ports:
      - "0.0.0.0:61231:80"
    networks:
      vologinsm-my-netology-hw:
        ipv4_address: 172.22.0.3
    depends_on:
      - vologinsm-netology-db
    restart: always

  vologinsm-zabbix-netology:
    image: zabbix/zabbix-server-pgsql
    links:
      - vologinsm-netology-db
    container_name: vologinsm-zabbix-netology
    environment:
      DB_SERVER_HOST: '172.22.0.2'
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: vologinsm12!3!!
    ports:
      - "0.0.0.0:10051:10051"
    networks:
      vologinsm-my-netology-hw:
        ipv4_address: 172.22.0.4
    depends_on:
      - vologinsm-netology-db
    restart: always

  vologinsm-netology-zabbix-frontend:
    image: zabbix/zabbix-web-apache-pgsql
    links:
      - vologinsm-netology-db
      - vologinsm-zabbix-netology
    container_name: vologinsm-netology-zabbix-frontend
    environment:
      DB_SERVER_HOST: '172.22.0.2'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: vologinsm12!3!!
      ZBX_SERVER_HOST: "vologinsm-netology-zabbix-frontend"
      PHP_TZ: "Asia/Yekaterinburg"
    ports:
      - "0.0.0.0:80:8080"
      - "0.0.0.0:443:8443"
    networks:
      vologinsm-my-netology-hw:
        ipv4_address: 172.22.0.5
    depends_on:
      - vologinsm-netology-db
      - vologinsm-zabbix-netology
    restart: always

networks:
  vologinsm-my-netology-hw:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/24
