---
- name: Install Docker
  hosts: app
  become: true
  remote_user: yeti
  tasks:
    - name: Remove non-offical packages
      ansible.builtin.apt:
        state: absent
        pkg:
          - docker.io
          - docker-doc
          - docker-compose
          - podman-docker
          - containerd
          - runc

    - name: Install packages depedencies
      ansible.builtin.apt:
        state: latest
        update_cache: true
        pkg:
          - apt-transport-https
          - ca-certificates
          - lsb-release
          - gnupg

    - name: Configuring official Docker repository
      block:
      - name: Create a directory if it does not exist
        ansible.builtin.file:
          path: /etc/apt/keyrings
          state: directory
          mode: u=rwx,g=rx,o=rx

      - name: Add signing key for official Docker repository
        ansible.builtin.get_url:
          url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
          dest: /etc/apt/keyrings/docker.asc
          mode: u=rwx,g=rx,o=rx

      - name: Add official Docker repository
        ansible.builtin.apt_repository:
          repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
          state: present
          filename: docker

      - name: Install all Docker's packages
        ansible.builtin.apt:
          state: latest
          update_cache: true
          pkg:
            - docker-ce
            - docker-ce-cli
            - containerd.io
            - docker-buildx-plugin
            - docker-compose-plugin

    - name: Add user to docker group
      ansible.builtin.user:
        name: "{{ ansible_user_id }}"
        groups: docker
        append: true

    - name: Restart Docker service
      ansible.builtin.systemd:
        name: docker
        state: restarted

    - name: Add run script
      ansible.builtin.copy:
        src: run.sh
        dest: /opt
        owner: root
        group: root
        mode: '0700'
