---
- name: Deploy Apache webserver with health status
  hosts: lab1
  become: true
  roles:
     - web_server
  tasks:
    - name: Check website availability
      ansible.builtin.uri:
        url: "http://{{ ansible_default_ipv4.address }}"
        method: GET
      register: response
      ignore_errors: yes

    - name: Show response of website 
      ansible.builtin.debug:
        var: response.status
