---
- name: Homework change motd
  hosts: lab1
  become: true
  vars:
    custom_message: "That's message configure by Ansible"

  tasks:
    - name: Find files for change permissions
      ansible.builtin.find:
        paths: /etc/update-motd.d/
        recurse: yes
        exclude: '99-custom'
      register: change

    - name: Change files permissions
      ansible.builtin.file:
        path: "{{ item.path }}"
        mode: '0400' 
      with_items: "{{ change.files }}"

    - name: Create 99-custom motd file
      ansible.builtin.file:
        path: /etc/update-motd.d/99-custom
        state: touch
        mode: '0755'
    
    - name: Change motd message
      ansible.builtin.template:
        src: motd.j2
        dest: /etc/update-motd.d/99-custom
      notify: restart ssh

  handlers:
    - name: restart ssh
      ansible.builtin.service:
        name: ssh
        state: restarted