---
- name: Install & configure tuned
  hosts: lab2
  become: true
  tasks:
    - name: Install tuned
      ansible.builtin.apt:
        name: tuned
        state: present
        update_cache: yes

    - name: Start service tuned & autostart enable
      ansible.builtin.service:
        name: tuned
        state: started
        enabled: yes